### ISSUE TITLE
Is there an official date to start?

### ISSUE THREAD

**Issue by water-vapor** [DeepSE/DeepCodingBaselines#3]
I am a bit worried since I saw the other two have started yesterday, I am wondering if I should also start working now. I have an acm contest on June 26th and I need to prepare for it, so my progress may be slower before that. I am interested in implementing baseline 1, but I am not sure about the difficulty. If that paper is not appropriate for out current stage, please point it out and I will choose another.

**Comment by guxd** [comment]
Code for #14 is already released. Please implement one that has no code ready. What about #9 or #10? You can start as early as possible.
