### ISSUE TITLE
Clarification required on the topic

### ISSUE THREAD

**Issue by water-vapor** [DeepSE/DeepCodingBaselines#5]
I just received an email from UROP system, saying that the topic of the project has changed to __Neural Dialogue Systems with Diversity__. Does this mean I should change to baseline #9 and join their team (of two)? I am fine with either choice.

**Comment by guxd** [comment]
Hi Zixuan, baseline #15 is related to deep memory network (MEMN2N), though with a different application background. Our goal is to implement a QA system using the memory network model.  Please check chapter 5 in https://arxiv.org/pdf/1511.06931.pdf and try to reproduce the results of MEMN2N in the table.

**Comment by water-vapor** [comment]
Problem resolved via PM
